version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "quarterly"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "io.netty:*"
        versions: [">=4.2.0"]
