name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          [
            21,
            25,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: oracle
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false
          cache-overwrite-existing: true
          dependency-graph: generate-and-submit
      - name: Build with Gradle
        run: gradle build
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.welcome=never"
